# Этот конфиг можно использовать для перегрузки параметров докера с высшим приоритетом не зависимо от окружения.
# Для этого нужно скопировать этот файл в корень проекта. Он прописан в .gitignore по этому в репу не пападёт.
version: '3.9'

services:
    db:
        ports:
            - '5444:5432'

    pgbouncer:
        ports:
            - '6444:6432'

    nginx:
        volumes:
            - ./../var/nginx.conf:/etc/nginx/conf.d/default.conf

#    php-fpm:
#        build: ./php-fpm_dev # тут xDebug, который можно включить локально в docker-compose.local.yml
#            - './../var/log/php-${APP_ENV}-fpm_xdebug/:/var/log'
