framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    form:
        csrf_protection:
            enabled: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id:      session.handler.native_file
        cookie_secure:   auto
        cookie_lifetime: 604800 # 1 неделя
        cookie_samesite: lax
        save_path:       "%kernel.project_dir%/var/sessions/%kernel.environment%"
        storage_factory_id: session.storage.factory.native

    esi: false
    #fragments: true
    php_errors:
        log: true
