# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
imports:
    - { resource: '_local.yaml', ignore_errors: true }

parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:               # defines the scalar arguments once and apply them to any service defined/created in this file
            $currency:   "%env(default::CURRENCY)%"
            $dateDefaultTimezone: "%env(default::TIMEZONE)%"
            $tgBotName:  "%env(default::TG_BOT_NAME)%"
            $tgBotToken: "%env(default::TG_BOT_TOKEN)%"
            $isUserForm: "%env(bool:USER_FORM_ENABLE)%"
            $isInternalMessengerEnable: "%env(bool:INTERNAL_MESSENGER_ENABLE)%"

    _instanceof:
        # services whose classes are instances of CustomInterface will be tagged automatically
        Doctrine\Common\EventSubscriber:
            tags: ['doctrine.event_subscriber']

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    app.menu.main:
        class: App\Menu\MainMenu
        arguments: ['@knp_menu.factory']
        tags:
            - { name: knp_menu.menu_builder, method: top, alias: top } # The alias is what is used to retrieve the menu
            - { name: knp_menu.menu_builder, method: profile, alias: profile }
            - { name: knp_menu.menu_builder, method: manual, alias: manual }

    # Menu selected items
    app.menu.voter.request:
        class: App\Menu\RequestVoter
        arguments:
            - '@request_stack'
        tags:
            - { name: knp_menu.voter }

    Gedmo\Loggable\LoggableListener:
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    Gedmo\Sortable\SortableListener:
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    Gedmo\Sluggable\SluggableListener:
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    Gedmo\Timestampable\TimestampableListener:
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    Gedmo\Tree\TreeListener:
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    # @todo отрефакторить
    Coop\JointPurchaseBundle\:
        resource: '../src-vendor/JointPurchaseBundle/*'
        exclude: '../src-vendor/JointPurchaseBundle/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    Coop\JointPurchaseBundle\Controller\:
        resource: '../src-vendor/JointPurchaseBundle/Controller'
        tags: ['controller.service_arguments']

    SmartCore\Bundle\TexterBundle\:
        resource: '../src-vendor/TexterBundle/*'
        exclude: '../src-vendor/TexterBundle/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    SmartCore\Bundle\TexterBundle\Controller\:
        resource: '../src-vendor/TexterBundle/Controller'
        tags: ['controller.service_arguments']

# @todo отрефакторить
doctrine:
    orm:
        resolve_target_entities:
            Symfony\Component\Security\Core\User\UserInterface: 'App\Entity\User'
